// <auto-generated />
namespace Dot_Net_Assignment_Shivam_Rao_UID00817.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddedRestaurantIdToOrderesAndIndexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRestaurantIdToOrderesAndIndexes));
        
        string IMigrationMetadata.Id
        {
            get { return "202609221106288_AddedRestaurantIdToOrderesAndIndexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
